USE DBSecuenciaVertical;
GO

-- Tabla 1 EstadoCuenta
INSERT INTO EstadoCuenta (Descripcion)
VALUES ('Activo'),
	   ('Pausado'),
	   ('Baja');
GO

-- Tabla 2 TipoUsuario
INSERT INTO TipoUsuario ( Descripcion)
VALUES ('Administrador'),
       ('Autor'),
       ('Lector');
GO

-- Tabla 3 TipoLector
INSERT INTO TipoLector (Descripcion)
VALUES ('Free'),
       ('Premium');
GO

-- Tabla 4 Cuentas
INSERT INTO Cuentas(Nombre, Apellido, Apodo,
			Contrasenia, Email, Telefono, Biografia,
			IdEstadoCuenta, IdTipoUsuario, IdTipoLector)
VALUES ('Juan', 'Marquez', 'Juanjo', '89qw12nm', 'juanma@hotmail.com', '11-3452-9705', 'Biografía de Juan', 1, 1, NULL),
	   ('Luján', 'Gonzales', 'Lujosita', '1212asdf', 'lujo@yahoo.com.ar', '11-3409-1212', 'Biografía de Luján', 1, 3, 2),
	   ('Héctor', 'Bertone', NULL,'12lk45oi', 'berto@gmail.com', NULL, 'Biografía de Héctor', 1, 2, NULL),
	   ('Delfina', 'Dhela', NULL, 'DelFi5656', 'delfo@outlook.com', NULL, 'Biografía de Delfina', 2, 2, NULL),
	   ('Miguel', 'Lopez', 'El Pollo', 'elPo3434', 'elpollo@gmail.com', NULL, 'Biografía de Miguel', 3, 3, 1),
	   ('Marcos', 'Gaitán', 'Gaita', '9n7bMar', 'marquitos@hotmail.com', '11-2345-6543', NULL, 1, 2, NULL),
	   ('Brisa', 'Altamirano', 'La jefa', '21Bri2109', 'altamiranob@outlook.com', NULL, NULL, 1, 3, 1),
	   ('Wanda', 'Marquez', 'Wan','wan1111Da', 'one1wan@outlook.com', '11-3245-1234', 'Biografía de Wiguel', 1, 3, 1),
	   ('Gastón', 'Silva', 'Tonga','tonga0091', 'tonga@yahoo.com', NULL, 'Biografía de Gastón', 1, 2, NULL),
	   ('Luciano', 'Rey', 'ReyLu', 'luc123rey', 'lrey@gmail.com', NULL, NULL, 1, 2, NULL),
	   ('Sonia', 'Delgado', 'Soni','s0niaD!23', 'sonidg@gmail.com', '11-7654-0099', NULL, 2, 3, 2),
	   ('Isabel', 'Bazan', 'Isa','isbz89!', 'isabel@live.com.ar', NULL, NULL, 3, 3, 2),
	   ('Lucía', 'Cano', 'Lu','luC34#', 'lucano@gmail.com', '11-3000-2244', NULL, 1, 2, NULL),
	   ('Federico', 'Lopez', 'Fede', 'fede654Lo', 'flopez@gmail.com', NULL, NULL, 1, 2, NULL),
	   ('Sofía', 'Navarro', 'Sofi', 'sofia#nav', 'sofia@live.com', NULL, NULL, 1, 2, NULL),
	   ('Carla', 'Jiménez', 'Carlita', 'Carl33jm', 'carla@outlook.com', NULL, NULL, 1, 3, 2),
	   ('Fernando', 'Belizán',NULL,'FB1234on', 'ferchu@gmai.com', NULL, 'Biografía de Fernando', 1, 2, NULL),
	   ('Martín', 'Ruiz', 'Martu', 'mr1234pass', 'mruiz@live.com', '11-4599-8787', NULL, 1, 2, NULL),
	   ('Sofía', 'Navarro', 'Sofi', 'sofia#nav', 'sofia@live.com', NULL, NULL, 3, 3, 1),
	   ('Fernando', 'Belizán', NULL, 'FB1234on', 'ferchu@gmai.com', NULL, 'Biografía de Fernando', 1, 1, NULL),
	   ('Ramón', 'Diaz', 'ElNegro', 'Riber821', 'moncho@hotmail.com', '11-3476-1205', 'Biografía de Ramón', 1, 3, 1);
GO

-- Tabla 5 RedesSociales
INSERT INTO RedesSociales (IdCuenta, Url)
VALUES (1, 'https://facebook.com/juanjo89'),
	   (1, 'https://twitter.com/juanjo_89'),
	   (2, 'https://instagram.com/lujosita'),
	   (2, 'https://tiktok.com/@lujosita'),
	   (3, 'https://twitter.com/berto'),
	   (3, 'https://linkedin.com/in/hbertone'),
	   (4, 'https://linkedin.com/in/ddhela'),
	   (4, 'https://instagram.com/delfi_dhela'),
	   (5, 'https://instagram.com/elpollo'),
	   (5, 'https://twitter.com/elpollo'),
	   (6, 'https://tiktok.com/@gaita'),
	   (6, 'https://facebook.com/gaita.marcos'),
	   (7, 'https://facebook.com/lajefa'),
	   (7, 'https://tiktok.com/@lajefa_altamirano'),
	   (8, 'https://instagram.com/wan_marquez'),
	   (8, 'https://twitter.com/wan_marq'),
	   (9, 'https://twitter.com/tonga_silva'),
	   (9, 'https://linkedin.com/in/gaston-silva'),
	   (10, 'https://linkedin.com/in/rey_luciano'),
	   (10, 'https://tiktok.com/@reylu'),
	   (11, 'https://instagram.com/sonia_d'),
	   (11, 'https://facebook.com/sonia.delgado'),
	   (12, 'https://facebook.com/isa_bazan'),
	   (12, 'https://instagram.com/isa.bazan'),
	   (13, 'https://twitter.com/lucia_cano'),
	   (13, 'https://twitter.com/lucia_cano'),
	   (14, 'https://linkedin.com/in/fede_lopez'),
	   (14, 'https://instagram.com/fede.lopez'),
	   (15, 'https://tiktok.com/@sofi_navarro'),
	   (16, 'https://instagram.com/carlita_j'),
	   (16, 'https://linkedin.com/in/carlita-jimenez'),
	   (17, 'https://facebook.com/ferchu_b'),
	   (18, 'https://twitter.com/martu_4599'),
	   (19, 'https://instagram.com/sofi_navarro_alt'),
	   (20, 'https://linkedin.com/in/ferchu_admin');
GO

-- Tabla 6 Genero
INSERT INTO Genero (Descripcion)
VALUES ('Terror'),
	   ('Ciencia ficción'),
	   ('Realista'),
	   ('Comedia'),
	   ('Acción'),
	   ('Suspenso'),
	   ('Policial'),
	   ('Drama'),
	   ('Triler'),
	   ('Triler psicológico'),
	   ('Documental'),
	   ('Biográfico'),
	   ('Fantasía'),
	   ('Costumbrista'),
	   ('Psicológico');
GO

-- Tabla 7 EstadoPublicacion
INSERT INTO EstadoPublicacion (Descripcion)
VALUES ('Activo'),
       ('Pausado'),
       ('Eliminado');
GO

-- Tabla 8 Historietas
INSERT INTO Historietas(Nombre, Sinopsis, CantidadPaginasActuales, TotalPaginas,
			MaterialExtra, IdEstadoPublicacion, FechaProximaPublicacion)
VALUES ('Detective sin pista','Detective sin pista, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',30, 30, 0, 1, '2025-06-23'),
	   ('El relojero','El relojero, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',24, 36, 1, 1, '2025-06-24'),
	   ('El gato negro','El gato negro, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',18, 20, 0, 1, '2025-06-25'),
	   ('Magnífico','Magnífico, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',75, 100, 1, 2, '2025-01-13'),
	   ('El inspector lunar',' inspector lunar, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',20, 20, 0, 1, '2025-06-26'),
	   ('El encapuchado','El encapuchado, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',16, 18, 0, 3, '2024-05-21'),
	   ('Laberinto sin fin','Laberinto sin fin, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',8, 30, 1, 1, '2025-06-27'),
	   ('Secretos de la luna','Secretos de la luna, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',22, 50, 0, 2, '2025-04-05'),
	   ('El coleccionista de sombras',' coleccionista de sombras, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',30, 30, 1, 1, '2025-06-28'),
	   ('Ciudad en ruinas','Ciudad en ruinas, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',8, 8, 1, 1, '2025-06-29'),
	   ('La última hoja','La última hoja, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',35, 100, 1, 1, '2025-06-30'),
	   ('Cuentos del bosque','Cuentos del bosque, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',29, 30, 0, 1, '2025-07-01');
GO

-- Tabla 9 HistorietaGenero
INSERT INTO HistorietaGenero(IdHistorieta, IdGenero)
VALUES (1,4),(1,5),
	   (2,1),(2,7),
	   (3,6),
	   (4,5),
	   (5,10),
	   (6,13),
	   (7,8),(7,13),(7,15),
	   (8,11),
	   (9,9),
	   (10,2),
	   (11,3),
	   (12,15),(12,13),(12,3),(12,8);
GO

-- Tabla 10 Roles
INSERT INTO Roles (Descripcion)
VALUES ('Guión'),
	   ('Dibujo'),
	   ('Tinta'),
	   ('Color'),
	   ('Adaptación'),
	   ('Integral'),
	   ('Arte');
GO

-- Tabla 11 Integrantes
INSERT INTO Integrantes (IdHistorieta, IdRol, IdCuenta)
VALUES (1, 1, 3),   
	   (1, 2, 4),   
	   (1, 4, NULL),
	   (2, 1, 6),
	   (2, 3, NULL),
	   (2, 6, 9),
	   (3, 2, 10),
	   (3, 4, NULL),
	   (3, 7, 13),
	   (4, 5, 14),
	   (4, 1, NULL),
	   (4, 2, 15),
	   (5, 3, 17),
	   (5, 6, 18),
	   (5, 7, NULL),
	   (6, 1, 3),
	   (6, 4, NULL),
	   (6, 5, 4),
	   (7, 2, 6),
	   (7, 3, NULL),
	   (7, 6, 9),
	   (8, 1, 10),
	   (8, 7, NULL),
	   (8, 4, 13),
	   (9, 2, 14),
	   (9, 5, NULL),
	   (9, 3, 15),
	   (10, 6, 17),
	   (10, 1, NULL),
	   (10, 7, 18),
	   (11, 4, 3),
	   (11, 2, NULL),
	   (11, 5, 4),
	   (12, 1, 6),
	   (12, 3, NULL),
	   (12, 6, 9);
GO

-- Tabla 12 Capitulos
INSERT INTO Capitulos(IdHistorieta, Titulo, Descripcion, UrlImagenCaratula, Premium)
VALUES (1, 'Detective sin Pista', NULL, 'Imagenes/Detective_sin_pista/dsp_Caratula', 0),  --finalizada
	   (2, '#1. Cuenta regresiva', 'Alvaro tiene los días contados, pero no todo esta perdido.', 'Imagenes/El_relojero/erj_Caratula_1', 0),  -- en desarrollo
	   (2, '#2. Minutos', 'Solo 5 minutos los separa del desastre.', 'Imagenes/El_relojero/erj_Caratula_2', 0),
	   (2, '#3. Capítulo extra', 'Martina no le cierran las cuentas, Alvaro esconde algo.', 'Imagenes/El_relojero/erj_Caratula_3', 1),
	   (3, 'El gato negro', 'Adaptación del cuento de Edgar Alan Poe', 'Imagenes/El_gato_negro/egn_Caratula', 0),  -- en desarrollo
	   (4, '#1. Sentencia', NULL, 'Imagenes/Magnífico/mgn_Caratula1', 0),  --Pausada
	   (4, '#2. Retorno', NULL, 'Imagenes/Magnífico/mgn_Caratula2', 0),
	   (4, '# Material Extra', 'Ilustraciones, bocetos, fichas de personajes', 'Imagenes/Magnífico/mgn_Material_Extra', 0),
	   (5, '#1. El viaje', NULL, 'Imagenes/El_inpector_lunar/eil_Caratula1', 0),  --finalizada
	   (5, '#2. La luna', NULL, 'Imagenes/El_inpector_lunar/eil_Caratula2', 0),
	   (6, 'El encapuchado', '"El hombre vive en un mundo en el que cada ocurrencia está cargada con ecos y reminiscencias de lo que ha ocurrido antes."', 'Imagenes/El_encapuchado/enc_Caratula', 0), --Eliminado
	   (7, '#1. Puerta N°6', NULL, 'Imagenes/Laberinto_sin_fin/lsf_Caratula1', 0),  -- en desarrollo
	   (7, '#2. Debajo del puente', NULL, 'Imagenes/Laberinto_sin_fin/lsf_Caratula2', 0),
	   (7, '#3. En balcon cerrado', NULL, 'Imagenes/Laberinto_sin_fin/lsf_Caratula3', 0),
	   (7, '# El nido oculto', 'Lo que nadie ve a la luz del día', 'Imagenes/Laberinto_sin_fin/lsf_Caratula4', 1),
	   (8, '#1. El mar', NULL, 'Imagenes/Secretos_de_la_luna/sdl_Caratula1', 0),  -- pausado
	   (8, '#2. La noche', NULL, 'Imagenes/Secretos_de_la_luna/sdl_Caratula2', 0),
	   (8, '#3. Tus ojos', NULL, 'Imagenes/Secretos_de_la_luna/sdl_Caratula3', 0),
	   (8, '#4. Solos', NULL, 'Imagenes/Secretos_de_la_luna/sdl_Caratula4', 0), 
	   (9, 'El coleccionista de sombras', 'En las sombras uno se puede perder', 'Imagenes/El_coleccionista_de_sombras/cds_Caratula', 0),
	   (10, 'Ciudad en ruinas', NULL, 'Imagenes/Ciudad_en_ruinas/cer_Caratula', 0),
	   (11, '#1. El cuento', NULL, 'Imagenes/La_ultima_hoja/luh_Caratula', 0),
	   (11, '#2. Allá, a lo lejos', NULL, 'Imagenes/La_ultima_hoja/luh_Caratula1', 0),
	   (12, '#1. La jauría', NULL, 'Imagenes/Cuentos_del_bosque/dsp_Caratula1', 0),
	   (12, '#2. El panal y el oso', NULL, 'Imagenes/Cuentos_del_bosque/dsp_Caratula2', 0),
	   (12, '#3. Golondrina', NULL, 'Imagenes/Cuentos_del_bosque/dsp_Caratula3', 0);
GO

-- Tabla 13 Paginas
INSERT INTO Paginas(IdCapitulo, Orientacion, UrlPagina) 
VALUES  -- Detective sin pista, capitulo 1, horizontal
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_001.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_002.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_003.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_004.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_005.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_006.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_007.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_008.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_009.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_010.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_011.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_012.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_013.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_014.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_015.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_016.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_017.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_018.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_019.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_020.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_021.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_022.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_023.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_024.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_025.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_026.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_027.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_028.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_029.jpg'),
		(1,0,'Imagenes/Detective_sin_pista/h_dsp_030.jpg'),
		 -- Detective sin pista, capitulo 1, vertical
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_001.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_002.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_003.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_004.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_005.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_006.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_007.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_008.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_009.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_010.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_011.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_012.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_013.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_014.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_015.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_016.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_017.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_018.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_019.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_020.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_021.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_022.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_023.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_024.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_025.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_026.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_027.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_028.jpg'),
		(1,1,'Imagenes/Detective_sin_pista/v_dsp_029.jpg'),
		 -- Detective sin pista, capitulo 4, vertical
		(4,1,'Imagenes/Detective_sin_pista/v_dsp_030.jpg'),

		-- El relojero, capitulo 2, horizontal
		(2,0,'Imagenes/El_relojero/h_erj_001.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_002.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_003.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_004.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_005.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_006.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_007.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_008.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_009.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_010.jpg'),
		(2,0,'Imagenes/El_relojero/h_erj_011.jpg'),
		-- El relojero, capitulo 3, horizontal
		(3,0,'Imagenes/El_relojero/h_erj_012.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_013.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_014.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_015.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_016.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_017.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_018.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_019.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_020.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_021.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_022.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_023.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_024.jpg'),
		(3,0,'Imagenes/El_relojero/h_erj_025.jpg'),
		-- El relojero, capitulo 2, vertical
		(2,1,'Imagenes/El_relojero/v_erj_001.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_002.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_003.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_004.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_005.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_006.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_007.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_008.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_009.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_010.jpg'),
		(2,1,'Imagenes/El_relojero/v_erj_011.jpg'),
		-- El relojero, capitulo 3, vertical
		(3,1,'Imagenes/El_relojero/v_erj_012.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_013.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_014.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_015.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_016.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_017.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_018.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_019.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_020.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_021.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_022.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_023.jpg'),
		(3,1,'Imagenes/El_relojero/v_erj_024.jpg'),
		-- El relojero, capitulo 4, vertical
		(4,1,'Imagenes/El_relojero/v_erj_025.jpg'),

		--El gato negro, capitulo 5, horizontal
		(5,0,'Imagenes/El_gato_negro/h_egn_001.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_002.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_003.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_004.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_005.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_006.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_007.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_008.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_009.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_010.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_011.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_012.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_013.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_014.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_015.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_016.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_017.jpg'),
		(5,0,'Imagenes/El_gato_negro/h_egn_018.jpg'),
		--El gato negro, capitulo 5, vertical
		(5,1,'Imagenes/El_gato_negro/v_egn_001.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_002.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_003.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_004.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_005.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_006.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_007.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_008.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_009.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_010.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_011.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_012.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_013.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_014.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_015.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_016.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_017.jpg'),
		(5,1,'Imagenes/El_gato_negro/v_egn_018.jpg'),

		--Magnífico, capitulo 6, horizontal
		(6,0,'Imagenes/Magnífico/h_mgn_001.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_002.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_003.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_004.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_005.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_006.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_007.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_008.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_009.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_010.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_011.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_012.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_013.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_014.jpg'),
		(6,0,'Imagenes/Magnífico/h_mgn_015.jpg'),
		--Magnífico, capitulo 6, vertical
		(6,1,'Imagenes/Magnífico/v_mgn_001.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_002.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_003.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_004.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_005.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_006.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_007.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_008.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_009.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_010.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_011.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_012.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_013.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_014.jpg'),
		(6,1,'Imagenes/Magnífico/v_mgn_015.jpg'),
		--Magnífico, capitulo 7, horizontal
		(7,0,'Imagenes/Magnífico/h_mgn_016.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_017.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_018.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_019.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_020.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_021.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_022.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_023.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_024.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_025.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_026.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_027.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_028.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_029.jpg'),
		(7,0,'Imagenes/Magnífico/h_mgn_030.jpg'),
		--Magnífico, capitulo 7, vertical
		(7,1,'Imagenes/Magnífico/v_mgn_016.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_017.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_018.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_019.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_020.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_021.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_022.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_023.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_024.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_025.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_026.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_027.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_028.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_029.jpg'),
		(7,1,'Imagenes/Magnífico/v_mgn_030.jpg'),
		--Magnífico, capitulo 8, horizontal
		(8,0,'Imagenes/Magnífico/h_mgn_031.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_032.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_033.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_034.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_035.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_036.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_037.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_038.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_039.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_040.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_041.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_042.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_043.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_044.jpg'),
		(8,0,'Imagenes/Magnífico/h_mgn_045.jpg'),
		--Magnífico, capitulo 8, vertical
		(8,1,'Imagenes/Magnífico/v_mgn_031.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_032.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_033.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_034.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_035.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_036.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_037.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_038.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_039.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_040.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_041.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_042.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_043.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_044.jpg'),
		(8,1,'Imagenes/Magnífico/v_mgn_045.jpg'),

		--El inspector lunar, capitulo 9, horizontal
		(9,0,'Imagenes/El_inspector_lunar/h_eil_001.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_002.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_003.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_004.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_005.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_006.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_007.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_008.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_009.jpg'),
		(9,0,'Imagenes/El_inspector_lunar/h_eil_010.jpg'),
		--El inspector lunar, capitulo 9, vertical
		(9,1,'Imagenes/El_inspector_lunar/v_eil_001.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_002.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_003.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_004.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_005.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_006.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_007.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_008.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_009.jpg'),
		(9,1,'Imagenes/El_inspector_lunar/v_eil_010.jpg'),
		--El inspector lunar, capitulo 10, horizontal
		(10,0,'Imagenes/El_inspector_lunar/h_eil_011.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_012.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_013.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_014.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_015.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_016.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_017.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_018.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_019.jpg'),
		(10,0,'Imagenes/El_inspector_lunar/h_eil_020.jpg'),
		--El inspector lunar, capitulo 10, vertical
		(10,1,'Imagenes/El_inspector_lunar/v_eil_011.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_012.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_013.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_014.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_015.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_016.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_017.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_018.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_019.jpg'),
		(10,1,'Imagenes/El_inspector_lunar/v_eil_020.jpg'),
		--El encapuchado, capitulo 11, horizontal
		(11,0,'Imagenes/El_encapuchado/h_enc_001.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_002.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_003.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_004.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_005.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_006.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_007.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_008.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_009.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_010.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_011.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_012.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_013.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_014.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_015.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_016.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_017.jpg'),
		(11,0,'Imagenes/El_encapuchado/h_enc_018.jpg'),

		--El encapuchado, capitulo 11, vertical
		(11,1,'Imagenes/El_encapuchado/v_enc_001.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_002.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_003.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_004.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_005.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_006.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_007.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_008.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_009.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_010.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_011.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_012.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_013.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_014.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_015.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_016.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_017.jpg'),
		(11,1,'Imagenes/El_encapuchado/v_enc_018.jpg'),

		--Laberinto sin fin, capitulo 12, horizontal
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_001.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_002.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_003.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_004.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_005.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_006.jpg'),
		(12,0,'Imagenes/Laberinto_sin_fin/h_lsf_007.jpg'),
		--Laberinto sin fin, capitulo 13, horizontal
		(13,0,'Imagenes/Laberinto_sin_fin/h_lsf_008.jpg'),
		--Laberinto sin fin, capitulo 12, vertical
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_001.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_002.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_003.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_004.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_005.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_006.jpg'),
		(12,1,'Imagenes/Laberinto_sin_fin/v_lsf_007.jpg'),
		--Laberinto sin fin, capitulo 13, vertical
		(13,1,'Imagenes/Laberinto_sin_fin/v_lsf_008.jpg'),

		-- Secretos de la luna, capitulo 16, horizontal
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_001.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_002.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_003.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_004.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_005.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_006.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_007.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_008.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_009.jpg'),
		(16,0,'Imagenes/Secretos_de_la_luna/h_sdl_010.jpg'),
		-- Secretos de la luna, capitulo 17, horizontal
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_011.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_012.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_013.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_014.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_015.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_016.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_017.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_018.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_019.jpg'),
		(17,0,'Imagenes/Secretos_de_la_luna/h_sdl_020.jpg'),
		-- Secretos de la luna, capitulo 18, horizontal
		(18,0,'Imagenes/Secretos_de_la_luna/h_sdl_021.jpg'),
		(18,0,'Imagenes/Secretos_de_la_luna/h_sdl_022.jpg'),
		-- Secretos de la luna, capitulo 16, vertical
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_001.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_002.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_003.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_004.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_005.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_006.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_007.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_008.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_009.jpg'),
		(16,1,'Imagenes/Secretos_de_la_luna/v_sdl_010.jpg'),
		-- Secretos de la luna, capitulo 17, vertical
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_011.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_012.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_013.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_014.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_015.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_016.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_017.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_018.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_019.jpg'),
		(17,1,'Imagenes/Secretos_de_la_luna/v_sdl_020.jpg'),
		-- Secretos de la luna, capitulo 18, vertical
		(18,1,'Imagenes/Secretos_de_la_luna/v_sdl_021.jpg'),
		(18,1,'Imagenes/Secretos_de_la_luna/v_sdl_022.jpg'),

		-- Coleccionista de sombras, capitulo 20, horizontal
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_001.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_002.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_003.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_004.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_005.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_006.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_007.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_008.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_009.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_010.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_011.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_012.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_013.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_014.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_015.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_016.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_017.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_018.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_019.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_020.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_021.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_022.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_023.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_024.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_025.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_026.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_027.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_028.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_029.jpg'),
		(20,0,'Imagenes/Coleccionista_de_sombras/h_cds_030.jpg'),
		-- Coleccionista de sombras, capitulo 20, vertical
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_001.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_002.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_003.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_004.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_005.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_006.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_007.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_008.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_009.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_010.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_011.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_012.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_013.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_014.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_015.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_016.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_017.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_018.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_019.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_020.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_021.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_022.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_023.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_024.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_025.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_026.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_027.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_028.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_029.jpg'),
		(20,1,'Imagenes/Coleccionista_de_sombras/v_cds_030.jpg'),

		-- La última hoja, capitulo 22, horizontal
		(22,0,'Imagenes/La_última_hoja/h_luh_001.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_002.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_003.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_004.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_005.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_006.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_007.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_008.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_009.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_010.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_011.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_012.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_013.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_014.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_015.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_016.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_017.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_018.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_019.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_020.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_021.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_022.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_023.jpg'),
		(22,0,'Imagenes/La_última_hoja/h_luh_024.jpg'),
		-- La última hoja, capitulo 23, horizontal
		(23,0,'Imagenes/La_última_hoja/h_luh_025.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_026.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_027.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_028.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_029.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_030.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_031.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_032.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_033.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_034.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_035.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_036.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_037.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_038.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_039.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_040.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_041.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_042.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_043.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_044.jpg'),
		(23,0,'Imagenes/La_última_hoja/h_luh_045.jpg'),
		-- La última hoja, capitulo 22, vertical
		(22,1,'Imagenes/La_última_hoja/v_luh_001.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_002.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_003.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_004.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_005.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_006.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_007.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_008.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_009.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_010.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_011.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_012.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_013.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_014.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_015.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_016.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_017.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_018.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_019.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_020.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_021.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_022.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_023.jpg'),
		(22,1,'Imagenes/La_última_hoja/v_luh_024.jpg'),
		-- La última hoja, capitulo 23, vertical
		(23,1,'Imagenes/La_última_hoja/v_luh_025.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_026.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_027.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_028.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_029.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_030.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_031.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_032.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_033.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_034.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_035.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_036.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_037.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_038.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_039.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_040.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_041.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_042.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_043.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_044.jpg'),
		(23,1,'Imagenes/La_última_hoja/v_luh_045.jpg'),

		-- Cuentos del bosque, capitulo 24, horizontal
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_001.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_002.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_003.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_004.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_005.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_006.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_007.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_008.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_009.jpg'),
		(24,0,'Imagenes/Cuentos_del_bosque/h_cdb_010.jpg'),
		-- Cuentos del bosque, capitulo 25, horizontal
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_011.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_012.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_013.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_014.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_015.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_016.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_017.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_018.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_019.jpg'),
		(25,0,'Imagenes/Cuentos_del_bosque/h_cdb_020.jpg'),
		-- Cuentos del bosque, capitulo 26, horizontal
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_021.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_022.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_023.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_024.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_025.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_026.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_027.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_028.jpg'),
		(26,0,'Imagenes/Cuentos_del_bosque/h_cdb_029.jpg'),
		-- Cuentos del bosque, capitulo 24, vertical
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_001.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_002.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_003.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_004.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_005.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_006.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_007.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_008.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_009.jpg'),
		(24,1,'Imagenes/Cuentos_del_bosque/v_cdb_010.jpg'),
		-- Cuentos del bosque, capitulo 25, vertical
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_011.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_012.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_013.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_014.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_015.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_016.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_017.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_018.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_019.jpg'),
		(25,1,'Imagenes/Cuentos_del_bosque/v_cdb_020.jpg'),
		-- Cuentos del bosque, capitulo 26, vertical
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_021.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_022.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_023.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_024.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_025.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_026.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_027.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_028.jpg'),
		(26,1,'Imagenes/Cuentos_del_bosque/v_cdb_029.jpg');
GO

-- Tabla 14 Valores
INSERT INTO Valores (Descripcion)
VALUES ('No me gustó'),
       ('Podría mejorar'),
       ('Regular'),
       ('Buena'),
       ('Excelente');
GO

-- Tabla 15 Valoraciones
INSERT INTO Valoraciones (IdHistorieta, IdCuenta, IdValor)
VALUES (1, 1, 4),
	   (1, 5, 2),
	   (1, 9, 5),
	   (2, 2, 3),
	   (2, 10, 1),
	   (2, 15, 4),
	   (3, 4, 2),
	   (3, 6, 5),
	   (3, 12, 3),
	   (4, 3, 1),
	   (4, 7, 4),
	   (4, 14, 2),
   	   (5, 8, 5),
	   (5, 11, 3),
	   (5, 16, 2),
	   (6, 1, 1),
	   (6, 9, 5),
	   (6, 13, 4),
	   (7, 5, 3),
	   (7, 10, 2),
	   (7, 18, 1),
	   (8, 2, 5),
	   (8, 14, 4),
	   (8, 20, 3),
	   (9, 3, 2),
	   (9, 15, 1),
	   (10, 7, 4),
	   (10, 12, 5),
	   (11, 6, 3),
	   (11, 17, 2),
	   (12, 4, 1),
	   (12, 19, 5);
GO

-- Tabla 16 Comentarios
INSERT INTO Comentarios (IdCuenta, IdHistorieta, Comentario)
VALUES (1, 3, 'La historia está increíble, me encantaron los giros argumentales.'),
	   (2, 5, 'El estilo de dibujo es fantástico, muy detallado y vibrante.'),
	   (3, 1, 'Podrían desarrollar un poco más a los personajes.'),
	   (4, 7, 'Buen ritmo, me mantuvo enganchado de principio a fin.'),
	   (5, 2, 'El uso del color es excelente, crea una atmósfera genial.'),
	   (6, 9, 'Los diálogos son naturales y atrapantes.'),
	   (7, 4, 'No me gustó mucho el final, se sintió apresurado.'),
	   (8, 6, 'Me gusta cómo combinan el texto con las imágenes.'),
	   (9, 8, 'Los personajes tienen mucha personalidad.'),
	   (10, 10, 'Se nota el esfuerzo en cada página, buen trabajo.'),
	   (11, 12, 'Me encantaría ver más historias como esta.'),
	   (12, 11, 'Algunos paneles están demasiado cargados, cuesta seguir.'),
	   (13, 2, 'Muy buena trama, espero la próxima entrega.'),
	   (14, 4, 'Los colores resaltan mucho y aportan emoción.'),
	   (15, 7, 'Me pareció un poco confuso en algunos momentos.'),
	   (16, 1, 'La narrativa gráfica está muy bien lograda.'),
	   (17, 5, 'Súper recomendable para fans del género.'),
	   (18, 9, 'El ritmo podría ser más constante, pero está bien.'),
	   (19, 3, 'Me gusta que se arriesguen con la historia.'),
	   (20, 6, 'El dibujo es lo mejor, de verdad impresionan.'),
	   (1, 8, 'La combinación de texto e imagen está muy bien balanceada.'),
	   (2, 11, 'Esperaba un poco más de desarrollo en algunos personajes.'),
	   (3, 10, 'Los fondos están muy bien detallados, se nota el trabajo.'),
	   (4, 3, 'El guion es sólido, pero algunos diálogos podrían mejorar.'),
	   (5, 12, 'Me encantó la manera en que usan la perspectiva.'),
	   (6, 2, 'Las sombras y luces le dan mucha profundidad a las escenas.'),
	   (7, 9, 'A veces la historia se siente un poco lenta, pero vale la pena.'),
	   (8, 7, 'Los colores vivos realmente resaltan la acción.'),
	   (9, 1, 'Me gustó mucho la evolución de los personajes principales.'),
	   (10, 4, 'El ritmo es rápido, pero no se pierde la coherencia.'),
	   (11, 5, 'Hay algunas inconsistencias menores, pero nada grave.'),
	   (12, 6, 'El diseño de los personajes es muy original y atractivo.'),
	   (13, 8, 'Los efectos visuales le dan un toque especial a la historia.'),
	   (14, 10, 'Me gustaría que profundizaran más en el trasfondo.'),
	   (15, 11, 'El diálogo es natural y ayuda a entender mejor la trama.'),
	   (16, 3, 'Algunas escenas me parecieron confusas, quizás un poco más claras ayudarían.'),
	   (17, 2, 'La edición y maquetación están muy bien hechas.'),
	   (18, 1, 'Me encanta cómo se manejan las emociones en los personajes.'),
	   (19, 9, 'La historia tiene potencial para una segunda temporada.'),
	   (20, 7, 'Siento que podrían explotar más la ambientación.'),
	   (1, 5, 'Los detalles en las expresiones faciales están geniales.'),
	   (2, 6, 'Muy buen trabajo con las transiciones entre escenas.'),
	   (3, 4, 'El uso del color ayuda a marcar el tono de cada momento.'),
	   (4, 12, 'Los personajes secundarios también están bien construidos.'),
	   (5, 11, 'El final me dejó con ganas de más, buen trabajo.'),
	   (6, 8, 'La narrativa visual es muy clara y atractiva.'),
	   (7, 10, 'Me gusta cómo se combinan diferentes estilos artísticos.'),
	   (8, 1, 'Sería genial ver más variedad en las tramas.'),
	   (9, 3, 'Algunos diálogos suenan un poco forzados, pero es entendible.'),
	   (10, 2, 'Muy buena introducción, atrapante desde el principio.'),
	   (11, 9, 'Me sorprendió la complejidad de la historia, buen nivel.'),
	   (12, 7, 'Los efectos de luz son impresionantes, muy realistas.');
GO

INSERT INTO Comentarios (IdCuenta, IdHistorieta, Comentario, Advertencia)
VALUES (21, 11, 'Son todo unos XXXXXXXXX', 1),
	   (21, 3, 'Odio a la gente que XXXXXXXXXXXX', 1),
	   (21, 9, 'Carlos tomatelá XXXXXXXXXXXXXXXXXXXXXXXXX', 1),
	   (14, 8, 'Lo uniko q no es un secreto es que los autores son unos XXXXXXXXXXXX. jaja!', 1);
GO